#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug  9 13:47:39 2020

@author: nitolapio
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist

mnist = mnist.load_data() # Con esto importamos el dataset de MNIST

(X_train, y_train), (X_test, y_test) = mnist






